server:
  port: 9080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oto?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpcserver:
      host:
        - ${LOCAL--+-HOST:127.0.0.1}
      port:
        - 9878
      enableKeepAlive: true
      keepAliveWithoutCalls: true
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml
debug: true
